#ifndef __NYAN_nyancat_INC
#define __NYAN_nyancat_INC
// automatically generated by ./nyan-gen.
static EFI_GRAPHICS_OUTPUT_BLT_PIXEL nyancat[] = { 
// each chunk is pixel is a pixel 21890*0
};
#endif
